' Enable skins (doesn't really work yet it seems)
'skinparam useBetaStyle true

!define CrimsonRed #bf0000
!define FA(x) <font:Font Awesome 5 Free><U+x></font>

hide footbox
skinparam ArrowColor Black
skinparam BackgroundColor transparent
skinparam DefaultFontName "Noto Sans JP"
skinparam NoteBackgroundColor #e8e8e8
skinparam NoteBorderColor #cccccc
skinparam NoteBorderThickness 0.5
skinparam padding 2
skinparam ParticipantBackgroundColor transparent
skinparam ParticipantBorderColor CrimsonRed
skinparam SequenceDividerBackgroundColor CrimsonRed
skinparam SequenceDividerFontColor White
skinparam SequenceGroupBackgroundColor transparent
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam SequenceLifeLineBorderColor CrimsonRed
skinparam SequenceReferenceBackgroundColor CrimsonRed
skinparam SequenceReferenceFontColor White
skinparam SequenceReferenceHeaderBackgroundColor transparent
skinparam Shadowing false
skinparam TitleFontColor CrimsonRed
skinparam TitleFontName "Rakuten Sans Medium"
