' Enable skins (doesn't really work yet it seems)
'skinparam useBetaStyle true

!define CrimsonRed #bf0000
!define FA(x) <font:Font Awesome 5 Free><U+x></font>

hide footbox
skinparam {
  arrowColor black
  backgroundColor transparent
  defaultFontName "Rakuten Sans"
  padding 2
  shadowing false

  activity {
    backgroundColor white
    borderColor CrimsonRed
    shape rectangle
    diamond {
      backgroundColor white
      borderColor CrimsonRed
    }
  }

  condition {
    style inside
    endStyle hline
  }

  note {
    backgroundColor #e8e8e8
    borderColor #cccccc
    borderThickness 0.5
  }

  participant {
    backgroundColor transparent
    borderColor CrimsonRed
  }

  sequence {

    divider {
      backgroundColor CrimsonRed
      fontColor White
    }

    group {
      backgroundColor transparent
      body {
        backgroundColor transparent
      }
    }

    lifeLine {
      borderColor CrimsonRed
    }

    reference {
      backgroundColor CrimsonRed
      fontColor White
      header {
        backgroundColor transparent
      }
    }
  }

  title {
    fontColor CrimsonRed
  }
}
